### ISSUE TITLE
Hello, I have a question about wezterm

### ISSUE THREAD

**Issue by ghost** [espeon011/config_files#1]
https://github.com/espeon011/config_files/blob/4407f044af4eb684a9d37d688e8a4254ea2178d1/wezterm/wezterm.lua#L7
https://github.com/espeon011/config_files/blob/4407f044af4eb684a9d37d688e8a4254ea2178d1/wezterm/wezterm.lua#L13

Does the above code get the correct user name and host name when connecting to the server over ssh?

Looking forward to your reply

**Comment by espeon011** [comment]
Hello!
The answer is "No". The above configuration gets the local hostname and username running wezterm. 
I don't know how to get remote hostname and username via ssh...

**Comment by ghost** [comment]
> Hello!
> The answer is "No". The above configuration gets the local hostname and username running wezterm.
> I don't know how to get remote hostname and username via ssh...

thx...
